### ISSUE TITLE
score() or match is not working with pt::text() when the argument of pt::text() is the item of an array

### ISSUE THREAD

**Issue by simonhrogers** [sanity-io/GROQ#58]
I’ve found a possible bug with `score()`:

```
score(
  boost(name match $keyword, 10), 
  pt::text(biography[].text) match $keyword
  pt::text(biography[].entries[].text) match $keyword
)
``` 
pt::text(biography[].entries[].text) works in the body of a request, just not in score() – I get: Query error – score() function received unexpected expression.

Annoyingly, I need it to work for both to get the depth of search I’d like…

It also doesn’t seem to work with pt::text(biography[].text) but just didn’t actively throw an error. Although either works perfectly in the body of a request.

I am using API version `2021-03-25` and `"@sanity/client": "^2.7.1"`

Thank you!

**Comment by atombender** [comment]
Thanks for the bug report. I can confirm that this is wrong. We have a fix that should be released today.

(This issue should really have been created in the [Sanity repo](http://github.com/sanity-io/sanity), but no need to move it now that it's created.)

**Comment by atombender** [comment]
This should be fixed now. Can you try again?

**Comment by simonhrogers** [comment]
Thanks @atombender! Do I need to be using a specific version of the client and specific API version? e.g. `2021-04-16` or will `2021-03-25` still work?

I noticed that the Sanity client is on `2.8.0` now but this update was 3 days ago. I’m using `2.8.0` with `2021-04-16` but still not seeing anything. Please pardon my ignorance!

**Comment by atombender** [comment]
@simonhrogers You can use `2021-03-25`. Any date after this works, too, but will simply use `v2021-03-25`. The fix is to our backend API, not to the Sanity client.

> but still not seeing anything

Do you mean that it's still failing with the error, or something else?

**Comment by simonhrogers** [comment]
Ah brilliant thank you! OK in that case:

Yes, no error. 

BUT it still isn’t actually finding information I know to be there. For example, I can see the string that should be matched in the request response, however if I try to match anything in either of these cases:

```
pt::text(biography[].text) match $keyword,
pt::text(biography[].entries[].text) match $keyword
```

No results are found for these. But if I match a string field, I can see the contents of these and the text I am searching for. So it’s not that my GROQ is wrong, I mean... !

**Comment by atombender** [comment]
Unfortunately, it looks like you've encountered another edge case. `pt::text()` currently does not support arrays of Portable Text attributes. But we do have a fix that we'll likely get out the door on Monday.

**Comment by atombender** [comment]
Sorry about the delay, we're working on making sure that we are doing this right.

**Comment by simonhrogers** [comment]
Ah OK! Thanks @atombender that would be brilliant. I mean `pt::text()` does actually support arrays of Portable Text attributes – both the examples in my initial question return data as I’d expect when used within the body of a query, as far as I can tell from a quick test of a few cases. It’s more that specifically this breaks within the `score()` function

**Comment by atombender** [comment]
We have finally rolled out a fix that should take care of this. There was actually a couple of edge cases that were potentially preventing array access from working correctly, e.g. `pt::text(foo[].bar)`. Can you test that it works for you?

**Comment by simonhrogers** [comment]
@atombender Bingo! Thank you so much :-) I’ll let you know if I come across anything over the next couple of days, but this appears to work perfectly.

**Comment by atombender** [comment]
Awesome! Very happy to hear that. I will close this now, then.
